---
hostname: drone-pi-01

# The LTE interface is auto-detected. Set lte_iface_override only as a recovery override.
lte_ip: 178.160.252.170
lte_prefix: 30
lte_gateway: 178.160.252.169
lte_network: 178.160.252.168/30
lte_table: 100
lte_apn: internet
